### PR TITLE
Enforce MSRV

### LINKED ISSUE #427: msrv 1.65.0 doesn't work
Individual crates advertise `rust-version = 1.65.0`.

However, `russh-sftp = "2.0.5"` has dependencies that won't build on 1.65.0, e.g. `flurry`:
```plaintext
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
   --> /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/flurry-0.5.0/src/lib.rs:288:5
    |
288 | /     fn hash_one<T: std::hash::Hash>(&self, x: T) -> u64
289 | |     where
290 | |         Self: Sized,
291 | |     {
292 | |         self.0.hash_one(x)
293 | |     }
    | |_____^
```

`russsh`-> `russh-sftp 2.0.5` -> `flurry 0.5` and all 0.5.x versions of flurry require at least rust 1.71.

I also don't see anything in CI that tests that the msrv works. It's very hard to guarantee a reliable msrv without automated checks.

### PR DESCRIPTION
**Pull request by Eugeny**
Fixes #427

### CODE REVIEW

**Comment by ericseppanen** [comment]
Nice!
